// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://temdaxtxaqswzbajpegw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbWRheHR4YXFzd3piYWpwZWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Nzg1NjgsImV4cCI6MjA2NjE1NDU2OH0.to1bwrsshd36WBpKuAfVOUusq-XOqVqSmD3nsCQt-pI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);